//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukoCollectionsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YukoCollectionsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить список ссылок?.
        /// </summary>
        internal static string ClearUrlsCommand_Confirmation {
            get {
                return ResourceManager.GetString("ClearUrlsCommand.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очищать список ссылок коллекции перед добавлением?.
        /// </summary>
        internal static string DownloadAllCollectionsCommand_ClearUrls {
            get {
                return ResourceManager.GetString("DownloadAllCollectionsCommand.ClearUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить список ссылок перед добавлением?.
        /// </summary>
        internal static string GetUrlsFromMessageCollectionCommand_ClearUrls {
            get {
                return ResourceManager.GetString("GetUrlsFromMessageCollectionCommand.ClearUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить список элементов коллекции перед добавлением?.
        /// </summary>
        internal static string ImportMessageCollectionCommand_ClearItems {
            get {
                return ResourceManager.GetString("ImportMessageCollectionCommand.ClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить список ссылок перед добавлением?.
        /// </summary>
        internal static string ImportUrlsCommand_ClearUrls {
            get {
                return ResourceManager.GetString("ImportUrlsCommand.ClearUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json.
        /// </summary>
        internal static string JsonFile_Ext {
            get {
                return ResourceManager.GetString("JsonFile.Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Object Notation|*.json.
        /// </summary>
        internal static string JsonFile_Filter {
            get {
                return ResourceManager.GetString("JsonFile.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon program_icon {
            get {
                object obj = ResourceManager.GetObject("program_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить сообщение {0} из списка?.
        /// </summary>
        internal static string RemoveMessageCollectionItemCommand_Confirmation {
            get {
                return ResourceManager.GetString("RemoveMessageCollectionItemCommand.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить &quot;{0}&quot; из списка?.
        /// </summary>
        internal static string RemoveUrlCommand_Confirmation {
            get {
                return ResourceManager.GetString("RemoveUrlCommand.Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt.
        /// </summary>
        internal static string TextFile_Ext {
            get {
                return ResourceManager.GetString("TextFile.Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовый докуент|*.txt.
        /// </summary>
        internal static string TextFile_Filter {
            get {
                return ResourceManager.GetString("TextFile.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезаписать данные текущих коллекций? Это приведет к потере списка ссылок..
        /// </summary>
        internal static string UpdateMessageCollectionsCommand_Overwrite {
            get {
                return ResourceManager.GetString("UpdateMessageCollectionsCommand.Overwrite", resourceCulture);
            }
        }
    }
}
