//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukoBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YukoBot.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, эта команда доступна только администратору гильдии!.
        /// </summary>
        internal static string AdminCommand_AccessError {
            get {
                return ResourceManager.GetString("AdminCommand.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка сообщения об успешности выполнения команды `add` на сервере (сообщение будет приходить в ЛС, а не в канал где выполнена команда)..
        /// </summary>
        internal static string AdminCommand_AddCommandResponse {
            get {
                return ResourceManager.GetString("AdminCommand.AddCommandResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено!.
        /// </summary>
        internal static string AdminCommand_AddCommandResponse_Disabled {
            get {
                return ResourceManager.GetString("AdminCommand.AddCommandResponse.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включено!.
        /// </summary>
        internal static string AdminCommand_AddCommandResponse_Enabled {
            get {
                return ResourceManager.GetString("AdminCommand.AddCommandResponse.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запретить пользователю скачивать с этого сервера..
        /// </summary>
        internal static string AdminCommand_Ban {
            get {
                return ResourceManager.GetString("AdminCommand.Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник успешно забанен!.
        /// </summary>
        internal static string AdminCommand_Ban_MemberBanned {
            get {
                return ResourceManager.GetString("AdminCommand.Ban.MemberBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник уже забанен!.
        /// </summary>
        internal static string AdminCommand_Ban_MemberIsAlreadyBanned {
            get {
                return ResourceManager.GetString("AdminCommand.Ban.MemberIsAlreadyBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не могу забанить незарегистрированного участника!.
        /// </summary>
        internal static string AdminCommand_Ban_MemberIsNotRegistered {
            get {
                return ResourceManager.GetString("AdminCommand.Ban.MemberIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, самобан запрещен!.
        /// </summary>
        internal static string AdminCommand_Ban_Myself {
            get {
                return ResourceManager.GetString("AdminCommand.Ban.Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина бана участника сервера..
        /// </summary>
        internal static string AdminCommand_MemberBanReason {
            get {
                return ResourceManager.GetString("AdminCommand.MemberBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник {0} не забанен!.
        /// </summary>
        internal static string AdminCommand_MemberBanReason_MemberIsNotBanned {
            get {
                return ResourceManager.GetString("AdminCommand.MemberBanReason.MemberIsNotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, участник {0} не зарегистрирован!.
        /// </summary>
        internal static string AdminCommand_MemberBanReason_MemberIsNotRegistered {
            get {
                return ResourceManager.GetString("AdminCommand.MemberBanReason.MemberIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению причина бана не была указана..
        /// </summary>
        internal static string AdminCommand_MemberBanReason_ReasonForBanIsNotSpecified {
            get {
                return ResourceManager.GetString("AdminCommand.MemberBanReason.ReasonForBanIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить / Отключить уведомление о включении бота..
        /// </summary>
        internal static string AdminCommand_ReadyNotification {
            get {
                return ResourceManager.GetString("AdminCommand.ReadyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления отключены!.
        /// </summary>
        internal static string AdminCommand_ReadyNotification_Disabled {
            get {
                return ResourceManager.GetString("AdminCommand.ReadyNotification.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления включены!.
        /// </summary>
        internal static string AdminCommand_ReadyNotification_Enabled {
            get {
                return ResourceManager.GetString("AdminCommand.ReadyNotification.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не могу отправлять уведомления о том, когда проснусь. Канал для отправки системных уведомлений не задан!.
        /// </summary>
        internal static string AdminCommand_ReadyNotification_NotificationChannelIsNotSet {
            get {
                return ResourceManager.GetString("AdminCommand.ReadyNotification.NotificationChannelIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить канал для поиска сообщений для команды `add-by-id`..
        /// </summary>
        internal static string AdminCommand_SetArtChannel {
            get {
                return ResourceManager.GetString("AdminCommand.SetArtChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал для поиска сообщений успешно установлен!.
        /// </summary>
        internal static string AdminCommand_SetArtChannel_Installed {
            get {
                return ResourceManager.GetString("AdminCommand.SetArtChannel.Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать канал для отправки системных уведомлений..
        /// </summary>
        internal static string AdminCommand_SetNotificationChannel {
            get {
                return ResourceManager.GetString("AdminCommand.SetNotificationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал успешно установлен!.
        /// </summary>
        internal static string AdminCommand_SetNotificationChannel_Installed {
            get {
                return ResourceManager.GetString("AdminCommand.SetNotificationChannel.Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включить / Отключить уведомление о выключении бота..
        /// </summary>
        internal static string AdminCommand_ShutdownNotification {
            get {
                return ResourceManager.GetString("AdminCommand.ShutdownNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления отключены!.
        /// </summary>
        internal static string AdminCommand_ShutdownNotification_Disabled {
            get {
                return ResourceManager.GetString("AdminCommand.ShutdownNotification.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления включены!.
        /// </summary>
        internal static string AdminCommand_ShutdownNotification_Enabled {
            get {
                return ResourceManager.GetString("AdminCommand.ShutdownNotification.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не могу отправлять уведомления о том, когда пойду баиньки. Канал для отправки системных уведомлений не задан!.
        /// </summary>
        internal static string AdminCommand_ShutdownNotification_NotificationChannelIsNotSet {
            get {
                return ResourceManager.GetString("AdminCommand.ShutdownNotification.NotificationChannelIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя из забаненых (пользователю снова разрешено скачивать с этого сервера)..
        /// </summary>
        internal static string AdminCommand_UnBan {
            get {
                return ResourceManager.GetString("AdminCommand.UnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник не забанен!.
        /// </summary>
        internal static string AdminCommand_UnBan_MemberIsNotBanned {
            get {
                return ResourceManager.GetString("AdminCommand.UnBan.MemberIsNotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не могу разбанить незарегистрированного участника!.
        /// </summary>
        internal static string AdminCommand_UnBan_MemberIsNotRegistered {
            get {
                return ResourceManager.GetString("AdminCommand.UnBan.MemberIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник успешно разбанен!.
        /// </summary>
        internal static string AdminCommand_UnBan_MemberUnbanned {
            get {
                return ResourceManager.GetString("AdminCommand.UnBan.MemberUnbanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, саморазбан запрещен!.
        /// </summary>
        internal static string AdminCommand_UnBan_Myself {
            get {
                return ResourceManager.GetString("AdminCommand.UnBan.Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на тебя {0} | {1}help.
        /// </summary>
        internal static string Bot_Activity {
            get {
                return ResourceManager.GetString("Bot.Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, в команде `{0}` ошибка!.
        /// </summary>
        internal static string Bot_CommandErrored_ArgumentException {
            get {
                return ResourceManager.GetString("Bot.CommandErrored.ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не знаю команды `{0}`!.
        /// </summary>
        internal static string Bot_CommandErrored_CommandNotFoundException {
            get {
                return ResourceManager.GetString("Bot.CommandErrored.CommandNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, сейчас я не могу выполнять команды!.
        /// </summary>
        internal static string Bot_CommandErrored_ShutdownBotException {
            get {
                return ResourceManager.GetString("Bot.CommandErrored.ShutdownBotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, при выполнении команды произошла неизвестная ошибка, попробуйте обратиться к моему создателю!.
        /// </summary>
        internal static string Bot_CommandErrored_UnknownException {
            get {
                return ResourceManager.GetString("Bot.CommandErrored.UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, для того что бы узнать больше информации обо мне выполни команду `{0}info`..
        /// </summary>
        internal static string Bot_Description {
            get {
                return ResourceManager.GetString("Bot.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый день - новая возможность! Я готова вас радовать!.
        /// </summary>
        internal static string Bot_NotificationsService_Ready {
            get {
                return ResourceManager.GetString("Bot.NotificationsService.Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошего дня (вечера)! Хозяин сказал мне отдыхать по причине: {0}.
        /// </summary>
        internal static string Bot_NotificationsService_Shutdown {
            get {
                return ResourceManager.GetString("Bot.NotificationsService.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Спряталась за {0} и смотрит на {1}**.
        /// </summary>
        internal static string Bot_PingService_MemberIsNotRegistered {
            get {
                return ResourceManager.GetString("Bot.PingService.MemberIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Подбежала и обняла {0}**.
        /// </summary>
        internal static string Bot_PingService_MemberIsRegistered {
            get {
                return ResourceManager.GetString("Bot.PingService.MemberIsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовиться ко сну.
        /// </summary>
        internal static string Bot_Shutdown {
            get {
                return ResourceManager.GetString("Bot.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал для поиска сообщений.
        /// </summary>
        internal static string CommandArg_ArtChannel {
            get {
                return ResourceManager.GetString("CommandArg.ArtChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание ошибки. Убедительная просьба прикладывать как можно больше информации об ошибке (действия которые к ней привели, скриншоты и т.д.) к сообщению с данной командой..
        /// </summary>
        internal static string CommandArg_BugReportDescription {
            get {
                return ResourceManager.GetString("CommandArg.BugReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория или команда.
        /// </summary>
        internal static string CommandArg_CategoryOrCommand {
            get {
                return ResourceManager.GetString("CommandArg.CategoryOrCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал.
        /// </summary>
        internal static string CommandArg_Channel {
            get {
                return ResourceManager.GetString("CommandArg.Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id коллекции.
        /// </summary>
        internal static string CommandArg_CollectionId {
            get {
                return ResourceManager.GetString("CommandArg.CollectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название коллекции.
        /// </summary>
        internal static string CommandArg_CollectionName {
            get {
                return ResourceManager.GetString("CommandArg.CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое название коллекции.
        /// </summary>
        internal static string CommandArg_CollectionNewName_v1 {
            get {
                return ResourceManager.GetString("CommandArg.CollectionNewName_v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое название коллекции (если название коллекции содержит пробелы заключите его в кавычки: &quot;.
        /// </summary>
        internal static string CommandArg_CollectionNewName_v2 {
            get {
                return ResourceManager.GetString("CommandArg.CollectionNewName_v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старое название коллекции (если название коллекции содержит пробелы заключите его в кавычки: &quot;.
        /// </summary>
        internal static string CommandArg_CollectionOldName {
            get {
                return ResourceManager.GetString("CommandArg.CollectionOldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение, на которое нужно продлить премиум доступ. Если премиум доступ нужно уменьшить, то вводится отрицательное значение..
        /// </summary>
        internal static string CommandArg_ExtendPremiumValue {
            get {
                return ResourceManager.GetString("CommandArg.ExtendPremiumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единица измерения для значения. Возможные значения: day / d - день; month / m - месяц; year / y - год..
        /// </summary>
        internal static string CommandArg_ExtendPremiumValueType {
            get {
                return ResourceManager.GetString("CommandArg.ExtendPremiumValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true - включить / false - отключить.
        /// </summary>
        internal static string CommandArg_IsEnabled {
            get {
                return ResourceManager.GetString("CommandArg.IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник сервера.
        /// </summary>
        internal static string CommandArg_Member {
            get {
                return ResourceManager.GetString("CommandArg.Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id сообщения.
        /// </summary>
        internal static string CommandArg_MessageId {
            get {
                return ResourceManager.GetString("CommandArg.MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название или Id коллекции.
        /// </summary>
        internal static string CommandArg_NameOrIdCollection {
            get {
                return ResourceManager.GetString("CommandArg.NameOrIdCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        internal static string CommandArg_Reason {
            get {
                return ResourceManager.GetString("CommandArg.Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды этой категории доступны для зарегистрированных и не забаненых (на этом сервере) пользователей..
        /// </summary>
        internal static string CommandCategory_CollectionManagement_AccessError {
            get {
                return ResourceManager.GetString("CommandCategory.CollectionManagement.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление коллекциями.
        /// </summary>
        internal static string CommandCategory_CollectionManagement_Title {
            get {
                return ResourceManager.GetString("CommandCategory.CollectionManagement.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды этой категории доступны администратору гильдии и владельцу бота..
        /// </summary>
        internal static string CommandCategory_Management_AccessError {
            get {
                return ResourceManager.GetString("CommandCategory.Management.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды управления.
        /// </summary>
        internal static string CommandCategory_Management_Title {
            get {
                return ResourceManager.GetString("CommandCategory.Management.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользовательские команды.
        /// </summary>
        internal static string CommandCategory_User_Title {
            get {
                return ResourceManager.GetString("CommandCategory.User.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, эта команда доступна для зарегистрированных и не забаненых (на этом сервере) пользователей!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AccessError {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую коллекцию..
        /// </summary>
        internal static string ManagingСollectionsCommand_AddCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, у тебя уже есть такая коллекция! Id: {0}..
        /// </summary>
        internal static string ManagingСollectionsCommand_AddCollection_CollectionExists {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddCollection.CollectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция создана! Id: {0}..
        /// </summary>
        internal static string ManagingСollectionsCommand_AddCollection_Created {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddCollection.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, название коллекции не может быть пустым!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddCollection_NameIsEmpty {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddCollection.NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить вложенное сообщение в указанную коллекцию. Если коллекция не указана сообщение добавляется в коллекцию по умолчанию..
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, такой коллекции нет!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, во время добавления сообщения в коллекцию &quot;{0}&quot; произошла ошибка. Сообщение не добавлено в коллекцию!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_ErrorAddingItem {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.ErrorAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, данное сообщение уже добавлено в коллекцию &quot;{0}&quot;!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_ExistsInCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.ExistsInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение добавлено в коллекцию &quot;{0}&quot;!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_IsSuccess {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нельзя добавлять сообщение в коллекцию если у него нет вложений!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_NoAttachments {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.NoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нет вложенного сообщения!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollection_ReferencedMessageNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollection.ReferencedMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить указанное сообщение в указанную коллекцию. Если коллекция не указана сообщение добавляется в коллекцию по умолчанию..
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, канал для поиска сообщений по умолчанию не найден, обратитесь к администратору сервера!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_ArtChannelNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.ArtChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не смогла найти заданное сообщение в текущем канале!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_MessageNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не смогла найти заданное сообщение в текущем канале! Канал для поиска сообщений по умолчанию не установлен, пожалуйста обратитесь к администратору сервера!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_MessageNotFoundAndArtChannelNotSet {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.MessageNotFoundAndArtChannelNotSet" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, я не смогла найти заданное сообщение в канале для поиска сообщений!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_MessageNotFoundInArtChannel {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.MessageNotFoundInArtChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, у меня нет прав на чтение сообщений в канале для поиска сообщений!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_NoArtChannelAccess {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.NoArtChannelAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, у меня нет прав на чтение сообщений в текущем канале!.
        /// </summary>
        internal static string ManagingСollectionsCommand_AddToCollectionById_NoChannelAccess {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.AddToCollectionById.NoChannelAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все сообщения из коллекции..
        /// </summary>
        internal static string ManagingСollectionsCommand_ClearCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ClearCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция &quot;{0}&quot; очищена!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ClearCollection_Cleared {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ClearCollection.Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, такой коллекции нет!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ClearCollection_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ClearCollection.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, название или id коллекции не может быть пустым!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ClearCollection_NameOrIdIsEmpty {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ClearCollection.NameOrIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить коллекцию..
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, такой коллекции нет!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteCollection_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteCollection.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция &quot;{0}&quot; удалена!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteCollection_Deleted {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteCollection.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить сообщение из коллекции..
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, такой коллекции нет!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollection_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollection.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение {0} из коллекции &quot;{1}&quot; удалено!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollection_Deleted {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollection.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, сообщения {0} и так нет в коллекции!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollection_MessageNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollection.MessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нет вложенного сообщения!.
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollection_NoReferencedMessage {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollection.NoReferencedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить вложенное сообщение из коллекции..
        /// </summary>
        internal static string ManagingСollectionsCommand_DeleteFromCollectionRef {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.DeleteFromCollectionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вложенное сообщение конечным сообщением для промежутка (входит в промежуток) и добавить входящие в промежуток сообщения в заданную коллекцию. Если коллекция не указана сообщения добавляются в коллекцию по умолчанию..
        /// </summary>
        internal static string ManagingСollectionsCommand_End {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, начальное и конечное сообщение промежутка из разных каналов!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_DifferentChannels {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.DifferentChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения в коллекцию &quot;{0}&quot; успешно добавлены!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_EndOfExecution {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.EndOfExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, во время добавления сообщения в коллекцию &quot;{0}&quot; произошла ошибка. Добавлены не все сообщения!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_ErrorAddingItem {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.ErrorAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нет вложенного сообщения!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_NoReferencedMessage {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.NoReferencedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста задайте начальное сообщение промежутка!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_StartMessageIsNotSet {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.StartMessageIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста подождите, после завершения операции я изменю это сообщение!.
        /// </summary>
        internal static string ManagingСollectionsCommand_End_StartOfExecution {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.End.StartOfExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовать указанную коллекцию..
        /// </summary>
        internal static string ManagingСollectionsCommand_RenameCollection {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.RenameCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, переименовываемая коллекция несуществует!.
        /// </summary>
        internal static string ManagingСollectionsCommand_RenameCollection_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.RenameCollection.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, коллекция с названием &quot;{0}&quot; уже существует!.
        /// </summary>
        internal static string ManagingСollectionsCommand_RenameCollection_Exists {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.RenameCollection.Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция &quot;{0}&quot; переименована в &quot;{1}&quot;!.
        /// </summary>
        internal static string ManagingСollectionsCommand_RenameCollection_Renamed {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.RenameCollection.Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать список коллекций..
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowCollections {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, у тебя нет не одной коллекции!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowCollections_IsEmpty {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowCollections.IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать последние 25 сообщений коллекции..
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowItems {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, такой коллекции нет!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowItems_CollectionNotFound {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowItems.CollectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, эта коллекция пустая!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowItems_IsEmpty {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowItems.IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, название или id коллекции не может быть пустым!.
        /// </summary>
        internal static string ManagingСollectionsCommand_ShowItems_NameOrIdIsEmpty {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.ShowItems.NameOrIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задать вложенное сообщение начальным сообщением для промежутка (входит в промежуток)..
        /// </summary>
        internal static string ManagingСollectionsCommand_Start {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, не удалось задать начальное сообщение!.
        /// </summary>
        internal static string ManagingСollectionsCommand_Start_IsNotSet {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.Start.IsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальное сообщение промежутка заданно!.
        /// </summary>
        internal static string ManagingСollectionsCommand_Start_IsSet {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.Start.IsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нет вложенного сообщения!.
        /// </summary>
        internal static string ManagingСollectionsCommand_Start_NoReferencedMessage {
            get {
                return ResourceManager.GetString("ManagingСollectionsCommand.Start.NoReferencedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, эта команда доступна только владельцу бота!.
        /// </summary>
        internal static string OwnerCommand_AccessError {
            get {
                return ResourceManager.GetString("OwnerCommand.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продлить премиум доступ..
        /// </summary>
        internal static string OwnerCommand_ExtendPremium {
            get {
                return ResourceManager.GetString("OwnerCommand.ExtendPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хозяин! Пожалуйста, укажите единицу измерения для значения! {0}.
        /// </summary>
        internal static string OwnerCommand_ExtendPremium_IncorrectUnit {
            get {
                return ResourceManager.GetString("OwnerCommand.ExtendPremium.IncorrectUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хозяин! Данный участник сервера не зарегистрирован! {0}.
        /// </summary>
        internal static string OwnerCommand_ExtendPremium_MemberNotRegistered {
            get {
                return ResourceManager.GetString("OwnerCommand.ExtendPremium.MemberNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хозяин! Премиум доступ для {0} успешно продлен! {1}.
        /// </summary>
        internal static string OwnerCommand_ExtendPremium_Response {
            get {
                return ResourceManager.GetString("OwnerCommand.ExtendPremium.Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить новую ссылку для команды `app`..
        /// </summary>
        internal static string OwnerCommand_SetApp {
            get {
                return ResourceManager.GetString("OwnerCommand.SetApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хозяин! Ссылка на приложение установлена! {0}.
        /// </summary>
        internal static string OwnerCommand_SetApp_Response {
            get {
                return ResourceManager.GetString("OwnerCommand.SetApp.Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выключить бота..
        /// </summary>
        internal static string OwnerCommand_Shutdown {
            get {
                return ResourceManager.GetString("OwnerCommand.Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, причина выключения не указана! {0}.
        /// </summary>
        internal static string OwnerCommand_Shutdown_ReasonIsEmpty {
            get {
                return ResourceManager.GetString("OwnerCommand.Shutdown.ReasonIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошо, хозяин! {0}.
        /// </summary>
        internal static string OwnerCommand_Shutdown_Response {
            get {
                return ResourceManager.GetString("OwnerCommand.Shutdown.Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сведения о боте..
        /// </summary>
        internal static string OwnerCommand_Status {
            get {
                return ResourceManager.GetString("OwnerCommand.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сборка.
        /// </summary>
        internal static string OwnerCommand_Status_FieldAssembly_Title {
            get {
                return ResourceManager.GetString("OwnerCommand.Status.FieldAssembly.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата запуска.
        /// </summary>
        internal static string OwnerCommand_Status_FieldLaunchDate_Title {
            get {
                return ResourceManager.GetString("OwnerCommand.Status.FieldLaunchDate.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d, {1}h, {2}m, {3}s.
        /// </summary>
        internal static string OwnerCommand_Status_FieldWorkingHours_Description {
            get {
                return ResourceManager.GetString("OwnerCommand.Status.FieldWorkingHours.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время работы.
        /// </summary>
        internal static string OwnerCommand_Status_FieldWorkingHours_Title {
            get {
                return ResourceManager.GetString("OwnerCommand.Status.FieldWorkingHours.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, эта команда доступна для зарегистрированных пользователей!.
        /// </summary>
        internal static string RegisteredUserCommand_AccessError {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина бана на текущем сервере..
        /// </summary>
        internal static string RegisteredUserCommand_BanReason {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не забанены!.
        /// </summary>
        internal static string RegisteredUserCommand_BanReason_NotBan {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BanReason.NotBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению причина бана не была указана!.
        /// </summary>
        internal static string RegisteredUserCommand_BanReason_NotBanReason {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BanReason.NotBanReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщить об ошибке..
        /// </summary>
        internal static string RegisteredUserCommand_BugReport {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой, эта команда отключена!.
        /// </summary>
        internal static string RegisteredUserCommand_BugReport_Description_IsDisabled {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BugReport.Description.IsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простите, нельзя отправлять пустой баг-репорт! Баг-репорт должен содержать описание и/или вложения и/или быть ответом на другое сообщение!.
        /// </summary>
        internal static string RegisteredUserCommand_BugReport_Description_IsEmpty {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BugReport.Description.IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баг-репорт успешно отправлен!.
        /// </summary>
        internal static string RegisteredUserCommand_BugReport_Description_IsSuccess {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.BugReport.Description.IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать ссылку на скачивание актуальной версии клиента..
        /// </summary>
        internal static string RegisteredUserCommand_GetClientApp {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.GetClientApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка сообщения об успешности выполнения команды `add` в ЛС (работает если сообщения об успешности выполнения команды `add` отключены на сервере).
        /// </summary>
        internal static string RegisteredUserCommand_InfoMessagesInPM {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.InfoMessagesInPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключено!.
        /// </summary>
        internal static string RegisteredUserCommand_InfoMessagesInPM_Description_Disabled {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.InfoMessagesInPM.Description.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включено!.
        /// </summary>
        internal static string RegisteredUserCommand_InfoMessagesInPM_Description_Enabled {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.InfoMessagesInPM.Description.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать информацию о моей учетной записи бота..
        /// </summary>
        internal static string RegisteredUserCommand_Profile {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldBanList_IsEmpty {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldBanList.IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указана.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldBanList_ReasonNotSpecified {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldBanList.ReasonNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список текущих банов:.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldBanList_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldBanList.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний вход в приложение:.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldLastLogin_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldLastLogin.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отключены.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldOptionalNotifications_Disabled {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldOptionalNotifications.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Включены.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldOptionalNotifications_Enabled {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldOptionalNotifications.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необязательные уведомления:.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldOptionalNotifications_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldOptionalNotifications.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет. Истек {0}.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldPremium_Expired {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldPremium.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть. Истекает {0}.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldPremium_Expires {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldPremium.Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет..
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldPremium_NotSet {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldPremium.NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум:.
        /// </summary>
        internal static string RegisteredUserCommand_Profile_FieldPremium_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Profile.FieldPremium.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать настройки для подключения к боту..
        /// </summary>
        internal static string RegisteredUserCommand_Settings {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хост.
        /// </summary>
        internal static string RegisteredUserCommand_Settings_FieldHost_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Settings.FieldHost.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт.
        /// </summary>
        internal static string RegisteredUserCommand_Settings_FieldPort_Title {
            get {
                return ResourceManager.GetString("RegisteredUserCommand.Settings.FieldPort.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получить аватар пользователя.
        /// </summary>
        internal static string UserCommand_Avatar {
            get {
                return ResourceManager.GetString("UserCommand.Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать список команд и категорий, если для команды не указан аргумент. Если в качестве аргумента указана категория - показывает список комманд этой категории с их описанием, если указана команда - показывает ее полное описание..
        /// </summary>
        internal static string UserCommand_Help {
            get {
                return ResourceManager.GetString("UserCommand.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Алиасы:**.
        /// </summary>
        internal static string UserCommand_Help_AliasesSection {
            get {
                return ResourceManager.GetString("UserCommand.Help.AliasesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Аргументы:**.
        /// </summary>
        internal static string UserCommand_Help_ArgumentsSection {
            get {
                return ResourceManager.GetString("UserCommand.Help.ArgumentsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Необязательно, по умолчанию: {0}.
        /// </summary>
        internal static string UserCommand_Help_OptionalArgument {
            get {
                return ResourceManager.GetString("UserCommand.Help.OptionalArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **__Вариант {0}__**.
        /// </summary>
        internal static string UserCommand_Help_OptionsSection {
            get {
                return ResourceManager.GetString("UserCommand.Help.OptionsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о боте и его возможностях..
        /// </summary>
        internal static string UserCommand_Info {
            get {
                return ResourceManager.GetString("UserCommand.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет, я Юко. Бот созданный для быстрого скачивания картинок с каналов серверов (гильдий) дискорда. Так же я могу составлять коллекции из сообщений с картинками (или ссылками на картинки) для последующего скачивания этих коллекций..
        /// </summary>
        internal static string UserCommand_Info_EmbedDescription {
            get {
                return ResourceManager.GetString("UserCommand.Info.EmbedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный функционал доступен только зарегистрированным пользователям. Для просмотра всех доступных команд управления коллекциями воспользуйся командой `{0}help {1}`..
        /// </summary>
        internal static string UserCommand_Info_FieldCollectionManagement_Description {
            get {
                return ResourceManager.GetString("UserCommand.Info.FieldCollectionManagement.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление коллекциями.
        /// </summary>
        internal static string UserCommand_Info_FieldCollectionManagement_Title {
            get {
                return ResourceManager.GetString("UserCommand.Info.FieldCollectionManagement.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылки.
        /// </summary>
        internal static string UserCommand_Info_FieldLinks_Title {
            get {
                return ResourceManager.GetString("UserCommand.Info.FieldLinks.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум доступ позволяет заранее сохранять необходимые данные (при добавлении сообщения в коллекцию) для скачивания вложений из сообщения. Это в разы уменьшает время получения ссылок клиентом для скачивания вложений. На данный момент выдается моим хозяином..
        /// </summary>
        internal static string UserCommand_Info_FieldPremiumAccess_Description {
            get {
                return ResourceManager.GetString("UserCommand.Info.FieldPremiumAccess.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум доступ.
        /// </summary>
        internal static string UserCommand_Info_FieldPremiumAccess_Title {
            get {
                return ResourceManager.GetString("UserCommand.Info.FieldPremiumAccess.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться и получить пароль и логин от своей учетной записи или сбросить текущий пароль..
        /// </summary>
        internal static string UserCommand_Register {
            get {
                return ResourceManager.GetString("UserCommand.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль от учетной записи отправлен в ЛС..
        /// </summary>
        internal static string UserCommand_Register_Description_PasswordChange {
            get {
                return ResourceManager.GetString("UserCommand.Register.Description.PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно! Пароль и логин от учетной записи отправлены в ЛС..
        /// </summary>
        internal static string UserCommand_Register_Description_Register {
            get {
                return ResourceManager.GetString("UserCommand.Register.Description.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль сменен!.
        /// </summary>
        internal static string UserCommand_Register_DmTitle_PasswordChange {
            get {
                return ResourceManager.GetString("UserCommand.Register.DmTitle.PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация прошла успешно!.
        /// </summary>
        internal static string UserCommand_Register_DmTitle_Register {
            get {
                return ResourceManager.GetString("UserCommand.Register.DmTitle.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используй **{0}** или **{1}**.
        /// </summary>
        internal static string UserCommand_Register_FieldDmDescription_Login {
            get {
                return ResourceManager.GetString("UserCommand.Register.FieldDmDescription.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string UserCommand_Register_FieldDmTitle_Login {
            get {
                return ResourceManager.GetString("UserCommand.Register.FieldDmTitle.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        internal static string UserCommand_Register_FieldDmTitle_NewPassword {
            get {
                return ResourceManager.GetString("UserCommand.Register.FieldDmTitle.NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string UserCommand_Register_FieldDmTitle_Password {
            get {
                return ResourceManager.GetString("UserCommand.Register.FieldDmTitle.Password", resourceCulture);
            }
        }
    }
}
